using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assignment_1
{
    class Program
    {
        static void Main(string[] args)
        {
            Employee emp = new Employee();
            //property
            //emp.Name = "Amol";
            emp.Name = null;
            //Console.WriteLine(emp.Name);
           

            //readonly and autogenerated
           // empm.Empno = 1;
            //Console.WriteLine(emp.Empno);


            //decimal BASIC
            //emp.Basic = 99;
            emp.Basic= 101;
            Console.WriteLine(emp.Basic);



            //short Deptno
             emp.Deptno = 1;
            //emp.Deptno= -1;
            Console.WriteLine(emp.Deptno);
            


            //Method
            emp.GetNetSalary();
            Console.WriteLine(emp.GetNetSalary());


            //constructor overloading
            Employee emp1 = new Employee("Amol", 12306, 10);
            Employee emp2 = new Employee("Amol", 123456);
            Employee emp3 = new Employee("Amol");
            Employee emp4 = new Employee();



            //count auto

            Console.WriteLine("1=" + emp1.Empno);
            Console.WriteLine("2=" + emp2.Empno);
            Console.WriteLine("3=" + emp3.Empno);
            Console.WriteLine("4=" + emp4.Empno);
           


            Console.WriteLine(emp4.Empno);
            Console.WriteLine(emp3.Empno);
            Console.WriteLine(emp2.Empno);
            Console.WriteLine(emp1.Empno);

            Console.ReadLine();

           


        }
    }

    //creating a class Employee
    public class Employee
    {
        //property
        private string name;
        public string Name
        {
            set {
                if (value != null)
                    name = value;
                else
                    Console.WriteLine("Name should not be empty");
                return; 

            }
            get { 
                return name;
            }
        }

        //readonly and auto generated
        private int empno;
        public int Empno
        {
            set {
                empno = value;
            }
            get {
                return empno;
            }
        }

        //decimal  Basic

        private decimal basic;
        public decimal Basic
        {
            set {
                if (value > 100 && value <1000)
                    basic = value;
                else
                    Console.WriteLine("the given value is not in range between 100.12 to 200.00");
            }
            get { 
                return basic;
            }
        }

        //short DeptNo
        private short deptno;
        public short Deptno
        {
            set {
                if (value > 0)
                    deptno = value;
                else
                    Console.WriteLine("value is not greater than 0");
            }
            get {
                return deptno;
            }
        }

      

        //count empno autogenerate
        public static int count = 0;
        public Employee(string name=null, decimal basic=0, short deptno=0)
        {
            count++;
           Name = name;
            Basic = basic;
           Deptno = deptno;
            Empno = Employee.count;
            //Console.WriteLine(" 3 para const");

        }


        //Method
        public decimal GetNetSalary()
        {
            decimal salary;
            salary = basic * 10;
            return salary;
        }
    }
}


